framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000

            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            App\Message\NotifyMessage: async
