version: '3.8'

services:
  p2pay_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2pay_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - p2pay_mysql
    networks:
      - p2pay

  p2pay_nginx:
    image: nginx:alpine
    container_name: p2pay_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - p2pay_php
    networks:
      - p2pay

  p2pay_mysql:
    image: mysql:8.0
    container_name: p2pay_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - p2pay_mysql_data:/var/lib/mysql
    networks:
      - p2pay

volumes:
  p2pay_mysql_data:

networks:
  p2pay:
